#!/bin/sh

# Script Environment Variables
# -------------------------------------------------------------------------------------
# SYNOPKG_PKGNAME				=	Package identify which is defined in INFO
# SYNOPKG_PKGVER				=	Package version which is defined in INFO
# SYNOPKG_PKGDEST				=	Package destination path
# 									/volume[x]/@appstore/[Package Name]
# SYNOPKG_TEMP_UPGRADE_FOLDER 	= 	Temporary upgrade folder
#									/volume1/@tmp/synopkg.tmp/[Package Name]
# -------------------------------------------------------------------------------------

TIMESTAMP=$(date '+%Y-%m-%d%t%H:%M:%S')

case $SYNOPKG_DSM_LANGUAGE in
	ger)
	echo "<h3>Wichtiger Hinweis!</h3><span style=\"color: red;\">Mit diesem Update wird</span> die bisher in Basic Backup integrierte <span style=\"color: red;\">AutoPilot</span> Funktion als eigenständige App <span style=\"color: red;\">ausgelagert</span>. Du kannst auch weiterhin deine mit Basic Backup erstellen Datensicherungsaufträge über AutoPilot ausführen lassen, indem du dir die App <span style=\"color: green;\">AutoPilot für externe Datenträger</span> von meinem GitHub Repository unter<br /><br /><div style=\"text-align: center;\"><a href=\"https://github.com/toafez/AutoPilot/releases\">https://github.com/toafez/AutoPilot/releases</a></div><br />herunterlädst, installierst und entsprechend konfigurierst. <span style=\"color: red;\">An deinen externen Datenträgern</span> bzw. an der darauf liegenden Scriptdatei autopilot <span style=\"color: red;\">müssen keine Änderungen vorgenommen werden</span>." > $SYNOPKG_TEMP_LOGFILE
	;;
	enu)
	echo "<h3>Important note!</h3><span style=\"color: red;\">With this update,</span> the <span style=\"color: red;\">AutoPilot</span> function as a standalone app <span style=\"color: red;\">outsourced</span>. You can continue to run your backup jobs created with Basic Backup via AutoPilot by downloading the app <span style=\"color: green;\">AutoPilot for external media</span> from my GitHub repository at<br /><br /><div style=\"text-align: center;\">< a href=\"https://github.com/toafez/AutoPilot/releases\">https://github.com/toafez/AutoPilot/releases</a></div><br />download, install and <span style=\"color: red;\">No changes need to be made to your external data carriers</span> or to the script file autopilot <span style=\"color: red;\">on it </span>." > $SYNOPKG_TEMP_LOGFILE
	;;
esac

# Delete udev rules
# -------------------------------------------------------------------------------------

if [ "${pkgwizard_remove_settings}" == "true" ]; then
	if [ -f /usr/lib/udev/rules.d/99-autopilot.rules ]; then
		# Check if AutoPilot UDEV rule points to Basic Backup
		udev_appcheck=$(grep -w /usr/lib/udev/rules.d/99-autopilot.rules -e "BasicBackup")
		if [ -n "${udev_appcheck}" ]; then
			rm -f /usr/lib/udev/rules.d/99-autopilot.rules
			if [ ! -f /usr/lib/udev/rules.d/99-autopilot.rules ]; then
				/usr/bin/udevadm control --reload-rules
				echo ''${TIMESTAMP}' - AutoPilot UDEV rule has been deleted.' >> /tmp/${SYNOPKG_PKGNAME}.history
			else
				echo ''${TIMESTAMP}' - The AutoPilot UDEV rule could not be deleted.' >> /tmp/${SYNOPKG_PKGNAME}.history
				case $SYNOPKG_DSM_LANGUAGE in
					ger)
					echo "Hinweis: Die AutoPilot UDEV-Regel konnte nicht gelöscht werden. Um die UDEV-Regel manuell zu löschen, öffnen sie ein Terminal Fenster und geben ein: rm -f /usr/lib/udev/rules.d/99-autopilot.rules " > $SYNOPKG_TEMP_LOGFILE
					;;
					*)
					echo "Note: The AutoPilot UDEV rule could not be deleted. To delete the UDEV rule manually, open a terminal window and type: rm -f /usr/lib/udev/rules.d/99-autopilot.rules " > $SYNOPKG_TEMP_LOGFILE
					;;
				esac
			fi
		fi
	fi
	exit 0
elif [ "${pkgwizard_remove_settings}" == "false" ]; then
	exit 1
else
	exit 0
fi

