#!/bin/sh

# Script Environment Variables
# -------------------------------------------------------------------------------------
# SYNOPKG_PKGNAME				=	Package identify which is defined in INFO
# SYNOPKG_PKGVER				=	Package version which is defined in INFO
# SYNOPKG_PKGDEST				=	Package destination path
# 									/volume[x]/@appstore/[Package Name]
# SYNOPKG_TEMP_UPGRADE_FOLDER 	= 	Temporary upgrade folder
#									/volume1/@tmp/synopkg.tmp/[Package Name]
# -------------------------------------------------------------------------------------

TIMESTAMP=$(date '+%Y-%m-%d%t%H:%M:%S')

echo "Hello World!!" > $SYNOPKG_TEMP_LOGFILE

case $SYNOPKG_DSM_LANGUAGE in
ger)
echo "Mit diesem Update wird die bisher in Basic Backup integrierte <strong>AutoPilot Funktion</strong> als eigenständige App <strong>ausgelagert</strong>. Du kannst auch weiterhin deine mit Basic Backup erstellen Datensicherungsaufträge über AutoPilot ausführen lassen, indem du dir die App <strong>AutoPilot für externe Datenträger</strong> von meinem GitHub Repository unter <a href=\"https://github.com/toafez/AutoPilot/releases\">https://github.com/toafez/AutoPilot/releases</a> herunterlädst, installierst und entsprechend konfigurierst. An deinen externen Datenträgern bzw. an der darauf liegenden Scriptdatei <strong>Gautopilot</strong> müssen jedoch keine weiteren Änderungen vorgenommen werden." > $SYNOPKG_TEMP_LOGFILE
;;
enu)
echo "With this update, the <strong>AutoPilot function</strong> that was previously integrated into Basic Backup is <strong>outsourced</strong> as an independent app. You can still run your backup jobs created with Basic Backup via AutoPilot by downloading the <strong>AutoPilot for External Disks</strong> app from my GitHub repository at <a href=\"https://github.com/toafez/AutoPilot/releases\">https://github.com/toafez/AutoPilot/releases</a> download, install and configure accordingly. However, no further changes need to be made to your external data carriers or to the <strong>autopilot</strong> script file on them." > $SYNOPKG_TEMP_LOGFILE
;;

# Backup user settings
# -------------------------------------------------------------------------------------
if [ ! -d "${SYNOPKG_TEMP_UPGRADE_FOLDER}/usersettings" ]; then
	mkdir -p -m 755 ${SYNOPKG_TEMP_UPGRADE_FOLDER}/usersettings
fi

echo ''${TIMESTAMP}' - Start package update --> '${SYNOPKG_PKGNAME}' '${SYNOPKG_PKGVER}'' >>/tmp/${SYNOPKG_PKGNAME}.history

if [ -d "${SYNOPKG_PKGDEST}/ui/usersettings" ]; then
    cp -rf ${SYNOPKG_PKGDEST}/ui/usersettings/* ${SYNOPKG_TEMP_UPGRADE_FOLDER}/usersettings
	echo ''${TIMESTAMP}' - Backup user settings from '${SYNOPKG_PKGDEST}'/ui/usersettings to '${SYNOPKG_TEMP_UPGRADE_FOLDER}'/usersettings' >>/tmp/${SYNOPKG_PKGNAME}.history
else
		echo ''${TIMESTAMP}' - Backup user settings failed' >>/tmp/${SYNOPKG_PKGNAME}.history
fi

exit 0